/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	init(A);
	init(D);

	pinMode(D, 13, OUTPUT);
	pinMode(A, 0, INPUT);

	uint8_t led_status = 0;      // LED initially OFF
	uint8_t prev_button_state = 0;  // Previous button state
	for (;;) {
		uint8_t button_state = readPin(A, 0);

		if (button_state && !prev_button_state) {
			led_status = !led_status;

			if (led_status) {
				writePin(D, 13, HIGH);
			} else {
				writePin(D, 13, LOW);
			}
		}
		prev_button_state = button_state;
		delay();
	}
}

void init(Port port)
{
	uint32_t volatile *clk_ctrl_reg_ptr = (uint32_t*) RCC_AHB1ENR_REG;
	uint32_t volatile *port_a_mode_in_reg_ptr = (uint32_t*) (PORTA_REG + PORT_INPUT_OFFSET);

	*clk_ctrl_reg_ptr |= (1 << port); // Enable the clock GPIOD peripheral in the AHB1ENR
}

void pinMode(Port port, uint8_t pin_num, PinMode mode)
{
	int volatile pin_index = pin_num * 2;

	// The reason for using volatile is to prevent the compiler from interpreting the variable.
	uint32_t volatile port_addres = PORTA_REG + (int)port * PORT_OFFSET;
	uint32_t volatile *port_mode_reg_ptr = (uint32_t*)(port_addres);

	// Clear the x and (x + 1) bit positions
	*port_mode_reg_ptr &= ~(3 << pin_index);
	switch (mode){
		case OUTPUT:
			*port_mode_reg_ptr |= (1 << pin_index); // make x bit position as 1
			break;
		case INPUT:
			break;
		default:
			break;
	}
}

uint8_t readPin(Port port, uint8_t pin_num)
{
	uint32_t volatile port_addres = PORTA_REG + (int)port * PORT_OFFSET;
	uint32_t volatile *port_mode_in_reg_ptr = (uint32_t*)(port_addres + PORT_INPUT_OFFSET);
	return ((uint8_t) (*port_mode_in_reg_ptr & 0x1));
}

void writePin(Port port, uint8_t pin_num, PinState state)
{
	uint32_t volatile port_addres = PORTA_REG + (int)port * PORT_OFFSET;
	uint32_t volatile *port_mode_out_reg_ptr = (uint32_t*)(port_addres + PORT_OUTPUT_OFFSET);
	if(state == HIGH) {
		*port_mode_out_reg_ptr |= (1 << 13);
	} else {
		*port_mode_out_reg_ptr &= ~(1 << 13);
	}
}

void delay()
{
	for (volatile int i = 0; i < 100000; i++);
}
