/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/*
	 * Bu kod, belirli iki bellek adresindeki verileri alıp,
	 * bu verileri toplar ve sonucu ikinci bellek adresine yazar.
 	 * Debug modunda sistemi başlatıp memory kısmından belirlenen
	 * adrese (0x20001000) değer girilip Register ekranından nasıl
	 * değişim olduğu izlenebilir.
	 */
#if 0
	__asm volatile("LDR R1, =#0x20001000"); // LDR (Load Register) Belirli bir adresi işaret etmeyi sağlar.
	__asm volatile("LDR R2, =#0x20001004");
	__asm volatile("LDR R0, [R1]"); // ADD(Addition) R1 değerinin R0 atanmasını sağlar.
	__asm volatile("LDR R1, [R2]");
	__asm volatile("ADD R0, R0, R1"); // R1 ve R0 değerlerinin toplamını R0 yazılmasını sağlar.
	__asm volatile("STR R0, [R2]"); // STR (Store Register) bir kayıttaki değeri bellekteki bir adrese yazar.
#endif
	int value = 50;
	/**
	 * Register değer yükler. %0 parametre tutucudur. "r" ifadesi, value'nin değerini bir genel
	 * amaçlı kayda (register) yükleyeceğimizi belirtir
	 */
	__asm volatile("MOV R0, %0"::"r"(value));
	for(;;);
}
